services:
  backend:
    build: ./backend
    ports:
      - "8011:8011"
  frontend:
    build: ./frontend
    ports:
      - "8012:8012"
    environment:
      - REACT_APP_API=http://backend:8011
    depends_on:
      - backend
